### ISSUE TITLE
update to 1.2

### ISSUE THREAD

**Issue by antonkulaga** [bytedeco/sbt-javacv#2]
Please, update preset loading to 1.2 (it is 1.1 right now)

**Comment by lloydmeta** [comment]
Hi there, I'll release a new version of this plugin with a version bump to 1.2 soon (currently on vacation), but until then, you can use `javaCVVersion := "1.2"`(declared [here](https://github.com/bytedeco/sbt-javacv/blob/master/src/main/scala/org/bytedeco/sbt/javacv/Plugin.scala#L32))  in your `Build.scala`/`build.sbt` to set it manually :)

**Comment by saudet** [comment]
I wonder, is there a way to query the central repository and use the latest
version by default? Would go against Maven's principles, but maybe that
would be OK for sbt?

**Comment by lloydmeta** [comment]
That is something you can definitely do in SBT, but I think it needs a bit more thought and likely should not be the default behaviour:
1. it assumes the ability to connect to Maven Central for the query
2. should probably have a fallback to a default version if querying fails
3. assumes that the user is ok with arbitrarily using the latest version, which can cause major compilation or runtime issues

For me, 3. is the biggest reason for not making this the default behaviour. That said, I'll leave a ticket open because it is a good idea (#3)

**Comment by lloydmeta** [comment]
I've just released a new version of this plugin that defaults to 1.2, so I'll close this issue now.
